-- Seed data generated from mockData.js
-- Courses and projects reference each other (courses.project_id <-> projects.course_id),
-- so we insert courses first with project_id left NULL, then projects, then backfill.

insert into public.courses (id, title, description, icon, difficulty, topics, project_id) values
('course-web-arch', 'Foundations of Web Architecture', 'How requests, servers, and browsers actually agree on anything. Start here before anything else.', 'Network', 'Beginner', '[{"id":"wa-t1","title":"The Request Lifecycle","children":[{"id":"wa-t1-s1","title":"DNS resolution and connection setup","xp":40},{"id":"wa-t1-s2","title":"HTTP methods and status codes","xp":40},{"id":"wa-t1-s3","title":"Headers, caching, and content negotiation","children":[{"id":"wa-t1-s3-a","title":"Cache-Control and ETags","xp":30},{"id":"wa-t1-s3-b","title":"Content-Type and Accept headers","xp":30}]}]},{"id":"wa-t2","title":"Client and Server Boundaries","children":[{"id":"wa-t2-s1","title":"Server-side vs client-side rendering","xp":45},{"id":"wa-t2-s2","title":"APIs, contracts, and statelessness","xp":45}]},{"id":"wa-t3","title":"Security Fundamentals","children":[{"id":"wa-t3-s1","title":"CORS and the same-origin policy","xp":50},{"id":"wa-t3-s2","title":"Authentication vs authorization","xp":50},{"id":"wa-t3-s3","title":"Common injection vectors","xp":55}]}]'::jsonb, NULL),
('course-db-eng', 'Database Engineering', 'Schemas, indexes, and the trade-offs that decide whether a query takes 4ms or 4 seconds.', 'Database', 'Intermediate', '[{"id":"db-t1","title":"Relational Modeling","children":[{"id":"db-t1-s1","title":"Normal forms and normalization","xp":45},{"id":"db-t1-s2","title":"Keys, constraints, and relationships","xp":45}]},{"id":"db-t2","title":"Indexing and Query Performance","children":[{"id":"db-t2-s1","title":"B-tree indexes and when they help","xp":55},{"id":"db-t2-s2","title":"Reading an execution plan","xp":55},{"id":"db-t2-s3","title":"N+1 queries and how to spot them","xp":50}]},{"id":"db-t3","title":"Transactions and Isolation","children":[{"id":"db-t3-s1","title":"ACID properties in practice","xp":50},{"id":"db-t3-s2","title":"Isolation levels and their trade-offs","xp":60}]}]'::jsonb, NULL),
('course-applied-ml', 'Applied Machine Learning', 'Building models that hold up outside the notebook — from clean data to a defensible evaluation.', 'BrainCircuit', 'Advanced', '[{"id":"ml-t1","title":"Data Preparation","children":[{"id":"ml-t1-s1","title":"Handling missing and skewed data","xp":50},{"id":"ml-t1-s2","title":"Feature scaling and encoding","xp":50}]},{"id":"ml-t2","title":"Model Selection","children":[{"id":"ml-t2-s1","title":"Bias-variance trade-off","xp":60},{"id":"ml-t2-s2","title":"Classical models","children":[{"id":"ml-t2-s2-a","title":"Linear and logistic regression","xp":40},{"id":"ml-t2-s2-b","title":"Decision trees and ensembles","xp":45}]}]},{"id":"ml-t3","title":"Evaluation Discipline","children":[{"id":"ml-t3-s1","title":"Train/validation/test splits","xp":45},{"id":"ml-t3-s2","title":"Precision, recall, and when each matters","xp":55}]}]'::jsonb, NULL),
('course-systems', 'Systems Programming Fundamentals', 'What''s actually happening below the language you learned first — memory, processes, and concurrency.', 'Cpu', 'Advanced', '[{"id":"sys-t1","title":"Memory Management","children":[{"id":"sys-t1-s1","title":"Stack vs heap allocation","xp":50},{"id":"sys-t1-s2","title":"Ownership and lifetimes","xp":60}]},{"id":"sys-t2","title":"Concurrency Primitives","children":[{"id":"sys-t2-s1","title":"Threads vs processes","xp":50},{"id":"sys-t2-s2","title":"Locks, mutexes, and race conditions","xp":60},{"id":"sys-t2-s3","title":"Message passing as an alternative","xp":55}]}]'::jsonb, NULL)
on conflict (id) do nothing;

insert into public.projects (id, course_id, title, description, requirements, xp_reward, difficulty) values
('proj-portfolio-api', 'course-web-arch', 'Build a Contract-First REST API', 'Design and ship a small REST API with documented endpoints, proper status codes, and CORS configured correctly.', ARRAY['At least 4 resource endpoints with correct HTTP verbs','Consistent error response shape','CORS configured for a named origin, not a wildcard','README documenting the contract']::text[], 200, 'Beginner'),
('proj-schema-design', 'course-db-eng', 'Design a Normalized Schema Under Load', 'Model a schema for a realistic domain, add the indexes it needs, and show a query plan improving after indexing.', ARRAY['Schema in at least 3rd normal form with a documented exception if any','Two indexes added with before/after EXPLAIN output','One transaction demonstrating isolation handling']::text[], 220, 'Intermediate'),
('proj-ml-pipeline', 'course-applied-ml', 'Ship a Reproducible ML Pipeline', 'Take a dataset from raw to evaluated model with a pipeline anyone else could re-run and get the same numbers from.', ARRAY['Data cleaning steps are scripted, not manual','Train/validation/test split with a fixed seed','Evaluation report with at least 2 relevant metrics']::text[], 260, 'Advanced'),
('proj-cli-tool', 'course-systems', 'Build a Concurrent CLI Tool', 'Write a command-line tool that processes multiple inputs concurrently without data races.', ARRAY['Correct use of threads or async tasks for concurrent work','No data races under the provided stress test','Clear usage documentation']::text[], 240, 'Advanced')
on conflict (id) do nothing;

update public.courses set project_id = 'proj-portfolio-api' where id = 'course-web-arch';
update public.courses set project_id = 'proj-schema-design' where id = 'course-db-eng';
update public.courses set project_id = 'proj-ml-pipeline' where id = 'course-applied-ml';
update public.courses set project_id = 'proj-cli-tool' where id = 'course-systems';